-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT
JOIN PATIENT ON PATIENT.PT_NO = APPOINTMENT.PT_NO
JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE SUBSTR(APNT_YMD,1,10) = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD