-- 코드를 작성해주세요
SELECT HE.DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES AS HE
INNER JOIN HR_DEPARTMENT AS HD
ON HE.DEPT_ID = HD.DEPT_ID
GROUP BY HE.DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC