-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN (SELECT * FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-01") AS S 
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC